SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8 ;
USE `chat` ;

DROP TABLE IF EXISTS `message` ;
DROP TABLE IF EXISTS `user_in_room` ;
DROP TABLE IF EXISTS `chat_room` ;
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
  `login` VARCHAR(16) NULL,
  `password` VARCHAR(128) NULL,
  `nickname` VARCHAR(16) NOT NULL UNIQUE,
  `creationTime` DATETIME NOT NULL,
  `isActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `chat_room` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creatorNickname` VARCHAR(16) NOT NULL,
  `creationTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `user_in_room` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `room_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

ALTER TABLE `user_in_room`
ADD CONSTRAINT `fk_userInroom_user_id`
FOREIGN KEY (`user_id`) REFERENCES `user`(`id`);

ALTER TABLE `user_in_room`
ADD INDEX `ix_userInroom_user_id`(`user_id`);

ALTER TABLE `user_in_room`
ADD CONSTRAINT `fk_userInroom_room_id`
FOREIGN KEY (`room_id`) REFERENCES `room`(`id`);

ALTER TABLE `user_in_room`
ADD INDEX `ix_userInroom_room_id`(`room_id`);


CREATE TABLE IF NOT EXISTS `message` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `creationTime` DATETIME NOT NULL,
  `user_nickname` VARCHAR(16) NOT NULL,
  `message_body` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

ALTER TABLE `message`
ADD CONSTRAINT `fk_message_room_id`
FOREIGN KEY(`room_id`) REFERENCES `chat_room`(`id`);

ALTER TABLE `message`
ADD INDEX `ix_message_room_id`(`room_id`);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
